# Docker Compose Override for Local Development
# This file extends docker-compose.yml for local development

version: '3.8'

services:
  # Override backend for local development
  backend:
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://defi_user:defi_password@postgres:5432/defi_tracker
      - SEI_RPC_URL=https://evm-rpc.sei-apis.com
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app
    command: ["uvicorn", "production_server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Override frontend for local development
  frontend:
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
